name: Build

on: push

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo check --workspace --all-targets
      - run: cargo build --workspace --all-targets
      - run: cargo run --workspace --all-targets
      - run: cargo test --workspace --all-targets

